version: '3'

services:
  web:
    build: ./
    ports:
      - "3001:3000"
    environment:
      - API_ENDPOINT=http://api:4567/api/
    links:
      - mongodb
  mongodb: 
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"